### PR TITLE
Break out protocol library

### PR DESCRIPTION
**Pull request by zml2008**
This allows WorldEdit to use this library as a JiJ'd mod, which avoids issues using integrated server in 1.20.6 caused by registering the same packet with two types (one from WE, the other from WECUI).

### CODE REVIEW

**Comment by mk-pmb** [comment]
Hi! I'm dissecting yours and luavixen's changes in hopes of reconciling the merge conflicts.
The benefit of @luavixen's branch is that it's compatible with 1.21, except it has the double packet registration bug in single player.
The benefit of your branch here is that it seems to solve the double packet registration, but it's not compatible with 1.21.
Both lack an (in case of luavixen, intermediate) step for compatibility with 1.20.6, which seems to be provided by 109 where unfortunately the discussion is locked.

I'd love to find a solution where we can each adjust our git histories to make it as easy as possible to merge all of those branches, ideally with proof of what has (not) changed, and I'm willing to construct those histories.

Would you be willing to help with making the branches easy to merge, even at the cost of having to rewrite your own branch history? The first and most blocking step would be to split dbd325f1cfc1d9948d724acf47d25042f117b74f ("rearrange project") into smaller parts that describe your actual intentions, and separate formalities like mass-rename from content changes.

As far as I can see, all the renames are 100%, which is good. To have any chance of merging though, I need the renames to happen first, one at a time. It looks like the first rename was
`git mv {,worldeditcui-fabric/}src/main/java/org/enginehub/worldeditcui`
so I tried to split that into its own commit and then rebase, but somehow that rebase fails, so it seems I have overlooked something.
I'd be willing to investigate further and try to guess what your intentions were, to then suggest to you an alternate history of this branch that documents those intentions, or at least splits your actions into smaller, easier to merge parts.

If you remember (or can reconstruct) what your renames were, and could find the time to split them out yourself (so they happen before the "rearrange project" commit), I'd love that even more of course.

Before I invest more effort though, I'd like to get your opinion on my approach. If you're not interested, I'll reduce the work that goes into making the history nice, and instead will optimize towards just making it work for 1.21 *somehow*, with no regard for the intermediate stage of supporting 1.20.6.

**Comment by zml2008** [comment]
no, we already have a 1.21 branch at https://github.com/EngineHub/WorldEditCUI/tree/mc/1.21, not sure why someone else decided to do one at random.

**Comment by mk-pmb** [comment]
Thanks! Probably because it was hard to discover. I should have just looked at the branch list. Probably the locked thread gave me a false impression of maintainers not being interested in updating. I'll have a look re-evaluate.

**Comment by mk-pmb** [comment]
I tried the 1.21 branch. It works, but as its ancestry suggests, it suffers from the double packet type registration problem in single player. So my new task is to merge this here pull request with the 1.21 branch, ideally with an intermediate step that merges #109 if you would like.
My current obstacle is the same as before: Splitting the big renames. How much would you like to be involved in helping with that (as described above)?

**Comment by zml2008** [comment]
Don't waste your time, the obstacle is setting up publishing and updating WE more than anything on the cui side, we can just rebase whenever that happens

**Comment by mk-pmb** [comment]
You mean, a merge here wouldn't solve the issue? It seems I'm missing something important then. Ok, where shall I invest my effort?

**Comment by mk-pmb** [comment]
Usually I'd edit, but seeing you reply by email you may miss that: I found [your WE pull request #2554 "Use WECUI protocol library"](https://github.com/EngineHub/WorldEdit/pull/2554) in draft status.
The second commit sounds like it should rather be and amend commit to the previous; shall I clean that up?

Or does "setting up publishing and updating WE" mean to set up a build pipeline for your pull request? I [have that for my own branch](https://github.com/mk-pmb/ghabuild-simple-gradle-projects/releases/tag/rolling/gh/enginehub/worldedit) and also [made one for the `feat/cui-proto-lib` branch](https://github.com/mk-pmb/ghabuild-simple-gradle-projects/blob/debug-gh/enginehub/worldedit/job.rc) but that [currently fails](https://github.com/mk-pmb/ghabuild-simple-gradle-projects/actions/runs/10558975058) with

```text
> Could not resolve all files for configuration ':worldedit-fabric:modImplementation'.
   > Could not find org.enginehub.worldeditcui:worldeditcui-protocol-fabric:1.20.6+01-SNAPSHOT.
```

Is that something I should try to fix? I'm a total noob to fabric, but I could try anyway.

**Pull request merged**
