### PR TITLE
1.20.6

### PR DESCRIPTION
**Pull request by zml2008**
For merging when final release happens

### CODE REVIEW

**Review by aurorasmiles — APPROVED** [review]

**Review by CyberFlameGO — APPROVED** [review]

**Comment by DaddyRobLIVE** [comment]
Please approve this PR

**Comment by CyberFlameGO** [comment]
I know the above comment was marked as spam but to address it - the PR's checks are caching the built mod artifact which you can use, and I've personally found no issues with this PR's builds if that's any help to you @DaddyRobLIVE :) Try the artifact here: https://github.com/EngineHub/WorldEditCUI/actions/runs/9539790119/artifacts/1606652226

**Comment by me4502** [comment]
The problem is that due to Fabric API changes, this cannot be run alongside WorldEdit, which is a majority of its use case. A workaround for the Fabric API issue is necessary before it can be properly released

**Comment by CyberFlameGO** [comment]
Ohh I'm assuming that's what #113 aims to achieve? That's my bad though :sob: I've only used it in conjunction with server-side WorldEdit

**Comment by luavixen** [comment]
I wanted to use WorldEditCUI on 1.21, so I updated the https://github.com/EngineHub/WorldEditCUI/tree/mc/1.20.5 branch to 1.21 in this commit on my fork: https://github.com/luavixen/WorldEditCUI/commit/b6e3cf98dab225f12acfcf3ec7187eb71a882906

Extremely minimal changes are required, and I would be happy to open a pull request or something else, but I don't want to interrupt your work.

**Comment by Ka1nnn** [comment]
> I wanted to use WorldEditCUI on 1.21, so I updated the https://github.com/EngineHub/WorldEditCUI/tree/mc/1.20.5 branch to 1.21 in this commit on my fork: [luavixen@b6e3cf9](https://github.com/luavixen/WorldEditCUI/commit/b6e3cf98dab225f12acfcf3ec7187eb71a882906)
> 
> Extremely minimal changes are required, and I would be happy to open a pull request or something else, but I don't want to interrupt your work.

this did not want to build for me it gave me this error 

image

**Comment by Phoenix616** [comment]
> > I wanted to use WorldEditCUI on 1.21, so I updated the [`mc`/1.20.5](https://github.com/EngineHub/WorldEditCUI/tree/mc/1.20.5?rgh-link-date=2024-07-01T23%3A18%3A09Z) branch to 1.21 in this commit on my fork: [luavixen@b6e3cf9](https://github.com/luavixen/WorldEditCUI/commit/b6e3cf98dab225f12acfcf3ec7187eb71a882906)
> > Extremely minimal changes are required, and I would be happy to open a pull request or something else, but I don't want to interrupt your work.
> 
> this did not want to build for me it gave me this error

Worked fine for me: [WorldEditCUI-1.21+01-SNAPSHOT-cleaned.jar.zip](https://github.com/user-attachments/files/16126351/WorldEditCUI-1.21%2B01-SNAPSHOT-cleaned.jar.zip), only weird thing is that it included the fabric dependency jars when running the `build` task. (I removed them manually from that jar)

**Comment by DaddyRobLIVE** [comment]
Can I please have 1.20.6 working dev build?

**Pull request merged**
