### PR TITLE
1.17

### PR DESCRIPTION
**Pull request by zml2008**
Will update occasionally throughout the snapshot process -- don't expect more than once a month though

### CODE REVIEW

**Comment by ColinTimBarndt** [comment]
I know that this branch is in development, though I'd like to point out that non-rectangular selectino markers (for the selection points, eg. cylinder center), the markers are still drawn when `//desel[ect]` is used. Instead, their coordinates are only set to (0, 0, 0). Except for the visual flickering because of the thin lines (which is WIP), the mod works flawlessly on the latest Fabric release (loader v0.11.6, api v0.35.1, MC v1.17). Thank you for updating this mod!

**Comment by TNTUP** [comment]
Can't wait to see it ready! Already upgraded my client to 1.17 (fabric) and this is the only mod I miss! Take your time, no rush. I subbed to this PR to keep an eye :)

**Comment by Greg-J** [comment]
Patiently waiting as well.

**Comment by mikroskeem** [comment]
Please refrain from adding comments which are essentially like "+1", simply use subscribe button on the right or add a reaction to the PR description if you want to show your interest publicly. Contributions are welcome - feel free to target this branch.

**Comment by ColinTimBarndt** [comment]
When investigating how the game renders the lines for structure blocks (package `net.minecraft.client.renderer.blockentity`), I noticed that it is using a buildin helper called `net.minecraft.client.renderer.LevelRenderer` and a VertexBuffer instead of the `GameRenderer` methods. This might contain some (good) code examples for how to render lines in 1.17.

I used https://github.com/hube12/DecompilerMC for decompiling the game.

**Comment by Drift91** [comment]
Not sure if you're aware, but 1.17.1 is out. I tried compiling this branch and running it on 1.17.1 and it throws the following: https://pastebin.com/nYVrDPr6

**Comment by andrewkm** [comment]
Same issue here.

**Comment by Samisaprogrammer** [comment]
Drift91 try without any mods except worldedit, worldeditCUI, and fabric api maybe?

**Comment by Samisaprogrammer** [comment]
Works for me. Fabric api 0.36.1, Fabric loader 0.11.6, Minecraft 1.17.1, Worldedit 7.2.6 beta 01 and this PR/branch compiled from gradle. 
image

**Comment by Drift91** [comment]
> 
> 
> Drift91 try without any mods except worldedit, worldeditCUI, and fabric api maybe?

Gah, I feel dumb now. I guess I assumed it wasn't a mod conflict since the same set of mods worked on 1.17.

Seems to be incompatible with OptiFabric. Not sure which mod is at fault though.

**Comment by Samisaprogrammer** [comment]
Rule of thumb never try dev branches/PRs without removing everything except the bare essentials.

**Comment by Drift91** [comment]
Just to let you know, Optifine compatibility seems to have been broken again sometime after [this commit](https://github.com/mikroskeem/WorldEditCUI/pull/34/commits/6e385ce27fca2d244aa74bc328e607cf7f435992). This time it launches fine but instead doesn't render the selection grid at all.

**Comment by MaxLevs** [comment]
> Just to let you know, Optifine compatibility seems to have been broken again sometime after [this commit](https://github.com/mikroskeem/WorldEditCUI/pull/34/commits/6e385ce27fca2d244aa74bc328e607cf7f435992). This time it launches fine but instead doesn't render the selection grid at all.

There are couple of mods that render through blocks well with mc 1.17.1 and installed letest pre optifine.
E.x. advanced x-ray

**Comment by TNTUP** [comment]
I know this is known and already reported, I have tested with:

fabric-loader-0.11.6-1.17.1
Optifine 1.17.1 HD U G9
Optifabric 0.11.20 (required for optifine to run)
fabric API 0.40.1+1.17
WorldEdit CUI 1.17.1+01-SNAPSHOT

Hope it helps!

**Comment by BSPiotr** [comment]
Having a weird issue where running the build from inside IntelliJ is not crashing anything, but building the .jar is crashing with a mixin error. Not sure where to go for help with this one.

**Comment by zml2008** [comment]
Superceded by #53

**Comment by joeyfigaro** [comment]
No chance of revisiting this? We're currently unable to upgrade beyond 1.17 and WorldEditCUI is a critical tool. 🔥

**Comment by BBloom81** [comment]
> No chance of revisiting this? We're currently unable to upgrade beyond 1.17 and WorldEditCUI is a critical tool. 🔥

What are you taking about?  It's available for up through 1.19 in the releases section.

Also, a cut is not a critical tool, it's a user enhancement tool at most.  It's great to have, but not necessary in any way for WorlsEdit to function correctly.

**Comment by zml2008** [comment]
You're welcome to figure out 1.17 builds yourself but they're not something we will ever bother with.

**Pull request closed without merging**
